name: cloud-ml
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - tensorflow==2.12.0
      - numpy
      - pandas
      - scikit-learn
      - flask
      - matplotlib
      - h5py